services:
  - type: web
    name: wacm-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: GATEWAY_URL
        value: "http://127.0.0.1:3001"
